import React, { FC, useState, useEffect } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/router'
import Head from 'next/head'
import { Container, Grid } from '@mui/material'
import ArrowBackIcon from '@mui/icons-material/ArrowBack'
import data from '../../data.json'
import Card from './components/Card'
import RestaurantInfo from './components/RestaurantInfo'
import { Brand, Item } from '../../inteface'
import Search from '../../common/Search'
import { Store, useStore } from '../../store'
import useStyles from './style'

const ProductsComponent: FC = () => {
  const { query } = useRouter()
  const { name } = query
  const [products, setProducts] = useState<Item[] | undefined>()
  const [brand, setBrand] = useState<Brand | undefined>()
  const { searchInput } = useStore((state: Store) => state)

  const getTargetProducts = () => {
    const brand = data.brands.find(item => item.name === name)
    setProducts(brand?.items)
    setBrand(brand)
  }

  useEffect(() => {
    getTargetProducts()
  }, [name])

  useEffect(() => {
    if (searchInput === '') {
      getTargetProducts()
    } else  setProducts(products?.filter(item => item.name.toLowerCase().includes(searchInput)))
  }, [searchInput, products?.length])

  const classes = useStyles()
  return (
    <>
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Search />
      <Container maxWidth="lg">
        <Grid container spacing={2}>
          <Grid item lg={12} md={12} sm={12} xs={12}>
            <div className={classes.productHeader}>
              <Link href="/">
                <a>
                  <ArrowBackIcon />
                </a>
              </Link>
              <h1> {name} </h1>
            </div>
          </Grid>
          <Grid item lg={12} md={12} sm={12} xs={12}>
            <RestaurantInfo brand={brand} />
          </Grid>
          {products &&
            products.map(product => (
              <Grid item lg={12} md={12} sm={12} xs={12} key={product.name}>
                <Card product={product} />
              </Grid>
            ))}
        </Grid>
      </Container>
    </>
  )
}

export default ProductsComponent
