import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Shop from '../modules/Shop'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Food App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Shop />
    </div>
  )
}

export default Home
